# Generated by Django 4.0.1 on 2022-06-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreAlumno', models.CharField(max_length=50)),
                ('Matricula', models.CharField(max_length=20)),
                ('Contraseña', models.CharField(max_length=20)),
                ('Tipocuenta', models.CharField(max_length=20, null=True)),
                ('Chat_id', models.CharField(max_length=40, null=True)),
                ('Token_tel', models.CharField(max_length=60, null=True)),
                ('Token_Env', models.CharField(max_length=60, null=True)),
                ('Token_Tem', models.DateTimeField(null=True)),
                ('salt', models.CharField(default='', max_length=100, null=True)),
                ('Estado_token', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IntentosIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(null=True, unique=True)),
                ('intentos', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('contraseña', models.CharField(max_length=100)),
            ],
        ),
    ]
