# Generated by Django 4.0.1 on 2022-06-23 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0006_profesor2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profesor2',
        ),
        migrations.AddField(
            model_name='archivosa',
            name='estado',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='practicas',
            name='practica_profesor',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='practica_profesor', to='modelo.profesor'),
            preserve_default='True',
        ),
    ]
