# Generated by Django 4.0.1 on 2022-06-07 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0002_alter_alumnos_chat_id_alter_alumnos_contraseña_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='Contraseña',
            field=models.CharField(max_length=100),
        ),
    ]
