# Generated by Django 4.0.1 on 2022-06-15 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0003_alter_alumnos_contraseña'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombrePractica', models.CharField(max_length=50)),
                ('Descripcion', models.TextField(max_length=200)),
                ('Entrada', models.CharField(max_length=30)),
                ('Esperada', models.CharField(max_length=30)),
                ('Archivo', models.FileField(upload_to='Practicas_Maestro/')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivosA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='Practicas/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.alumnos')),
            ],
        ),
    ]
