# Generated by Django 4.0.1 on 2022-06-22 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0005_profesor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreProfesor', models.CharField(max_length=50)),
                ('Matricula', models.CharField(max_length=20)),
            ],
        ),
    ]
