# Generated by Django 2.2.12 on 2022-05-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0004_alumnos_tipocuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='intentos',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ip',
            field=models.GenericIPAddressField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
