# Generated by Django 2.2.12 on 2022-05-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0005_auto_20220518_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnos',
            name='Chat_id',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
