# Generated by Django 2.2.12 on 2022-05-20 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0007_alumnos_token_tel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='intentos',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='alumnos',
            name='intentos',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='alumnos',
            name='ip',
            field=models.GenericIPAddressField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='alumnos',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
