# Generated by Django 2.2.12 on 2022-05-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0009_auto_20220520_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnos',
            name='Token_Env',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='alumnos',
            name='Token_Tem',
            field=models.DateTimeField(null=True),
        ),
    ]
