# Generated by Django 2.2.12 on 2022-05-24 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0010_auto_20220520_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnos',
            name='salt',
            field=models.CharField(default='', max_length=16, null=True),
        ),
    ]
