# Generated by Django 2.2.12 on 2022-05-25 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0011_alumnos_salt'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnos',
            name='Estado_token',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='salt',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
