# Generated by Django 3.2.13 on 2022-05-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0012_auto_20220525_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='Contraseña',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='intentosip',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
