# Generated by Django 2.2.12 on 2022-05-19 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0006_alumnos_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnos',
            name='Token_tel',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
