# Generated by Django 2.2.12 on 2022-05-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0008_auto_20220520_0552'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentosIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(null=True, unique=True)),
                ('intentos', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='intentos',
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='timestamp',
        ),
    ]
