# Generated by Django 4.0.4 on 2022-05-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0012_alter_alumnos_id_alter_intentosip_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='Contraseña',
            field=models.CharField(max_length=70),
        ),
    ]
