# Generated by Django 4.0.4 on 2022-05-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0013_alter_alumnos_contraseña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivosa',
            name='upload',
            field=models.FileField(upload_to='Proyecto/archivos/'),
        ),
    ]
