# Generated by Django 3.2.13 on 2022-05-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0017_auto_20220527_0122'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivosP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='Ejercicios/')),
            ],
        ),
    ]
