# Generated by Django 3.2.13 on 2022-05-30 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0018_archivosp'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivosp',
            name='NombreActividad',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
