# Generated by Django 3.2.13 on 2022-06-06 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0020_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivosp',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modelo.profesor'),
        ),
    ]
