# Generated by Django 3.2.13 on 2022-06-06 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0021_archivosp_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivosp',
            name='usuario',
        ),
    ]
